services:
  - type: web
    name: ddos-dashboard
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python generate_training_data.py && python train_model.py"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
  - type: web
    name: real-website
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn real_website.real_website:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
